FROM node:latest

WORKDIR /app/viteapp

COPY package.json .

RUN npm install

COPY . .

RUN npm run build 

EXPOSE 8080

COPY package.json .

COPY vite.config.js .

RUN npm install

CMD [ "npm","run","preview" ]