apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels: 
        app: mongodb 
    spec: 
      # nodeName: local-cluster-m02
      nodeSelector:
        team: devops
      tolerations:
        - key: "env"
          operator: Equal 
          value: "prod"
          effect: NoSchedule
      # affinity:
      #   nodeAffinity:
          # requiredDuringSchedulingIgnoredDuringExecution:
          #   nodeSelectorTerms:
          #     - matchExpressions:
          #         - key: "rank"
          #           operator: Lt
          #           values:
          #             - "0"
          # preferredDuringSchedulingIgnoredDuringExecution:
          #   - weight: 40
          #     preference:
          #       matchExpressions:
          #       - key: "team"
          #         operator: In
          #         values: ["analytics"]
          #   - weight: 60
          #     preference:
          #       matchExpressions:
          #       - key: "rank"
          #         operator: Gt
          #         values: ["4"]
      containers:
        - name: mongodbcont
          image: mongo 
          args: ["--dbpath", "/data/db"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-vol
      volumes:
        - name: mongo-vol
          emptyDir: {}