FROM node:latest as BUILD_IMAGE

WORKDIR /app/viteapp

COPY package.json .

RUN npm install

COPY . .

RUN npm run build 

#production image

FROM nginx:1.25.4 as PRODUCTION_IMAGE

WORKDIR /usr/share/nginx/html

COPY --from=BUILD_IMAGE /app/dist .

COPY --from=BUILD_IMAGE /app/conf.d conf.d

EXPOSE 8080 

COPY package.json .

COPY vite.config.js .

RUN npm install

CMD [ "npm","run","preview" ]