apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity: # for any pv, we should declare its capacity
    storage: 5Gi
  accessModes:
    - ReadWriteMany # means read,write by many nodes
    # These some other access modes
    # - ReadWriteOnce - means read write by only one node
    # - ReadOnlyOnce - read only by only one node
    # - ReadOnlyMany - read only by many nodes
    # - ReadWriteOncePod - read,write by only one pod.
  local:
    path: /storage/data # where the data should be stored.
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube