apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 
  storageClassName: "" 
  # here the accessmodes and resources will refer the persistent volume and choose the suitable one.
  
